// <auto-generated />
namespace AppGestionCahierText.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class MiseAJourModele : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MiseAJourModele));
        
        string IMigrationMetadata.Id
        {
            get { return "202602160919290_MiseAJourModele"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
